// A curated, always-available reference of core math & science formulas.
// Organized by discipline → category → formula. Equations use unicode so they
// render anywhere without a math renderer.

export const FORMULA_DISCIPLINES = [
  {
    id: "math",
    label: "Mathematics",
    categories: [
      {
        id: "algebra",
        label: "Algebra & Series",
        formulas: [
          { id: "alg-quad", name: "Quadratic Formula", eq: "x = (−b ± √(b² − 4ac)) / 2a", desc: "Roots of ax² + bx + c = 0." },
          { id: "alg-disc", name: "Discriminant", eq: "Δ = b² − 4ac", desc: "Δ>0 two real roots; Δ=0 one; Δ<0 complex." },
          { id: "alg-slope", name: "Slope-Intercept", eq: "y = mx + b", desc: "Line with slope m and y-intercept b." },
          { id: "alg-ptslope", name: "Point-Slope", eq: "y − y₁ = m(x − x₁)", desc: "Line through (x₁,y₁) with slope m." },
          { id: "alg-dist", name: "Distance Between Points", eq: "d = √((x₂−x₁)² + (y₂−y₁)²)", desc: "Straight-line distance in the plane." },
          { id: "alg-mid", name: "Midpoint", eq: "M = ((x₁+x₂)/2, (y₁+y₂)/2)", desc: "Center point of a segment." },
          { id: "alg-exp", name: "Exponent Rules", eq: "aᵐ·aⁿ = aᵐ⁺ⁿ · (aᵐ)ⁿ = aᵐⁿ · a⁰ = 1", desc: "Core laws of exponents." },
          { id: "alg-log", name: "Logarithm Rules", eq: "logₐ(xy) = logₐx + logₐy · logₐ(xⁿ) = n·logₐx", desc: "Product, power, quotient log laws." },
          { id: "alg-cob", name: "Change of Base", eq: "logₐx = log_b x / log_b a", desc: "Convert a log to any base." },
          { id: "alg-natlog", name: "Natural Log / e", eq: "ln(eˣ) = x · e^(ln x) = x", desc: "ln and e are inverses." },
          { id: "alg-binom", name: "Binomial Expansion", eq: "(a+b)ⁿ = Σ C(n,k) aⁿ⁻ᵏ bᵏ", desc: "Expand a binomial raised to n." },
          { id: "alg-comb", name: "Combinations", eq: "C(n,k) = n! / (k!(n−k)!)", desc: "Choose k of n, order irrelevant." },
          { id: "alg-perm", name: "Permutations", eq: "P(n,k) = n! / (n−k)!", desc: "Arrange k of n, order matters." },
          { id: "alg-arith", name: "Arithmetic Series", eq: "Sₙ = (n/2)(a₁ + aₙ)", desc: "Sum of an arithmetic progression." },
          { id: "alg-geom", name: "Geometric Series", eq: "Sₙ = a(1 − rⁿ)/(1 − r)", desc: "Finite geometric sum; |r|≠1." },
          { id: "alg-geominf", name: "Infinite Geometric Series", eq: "S∞ = a / (1 − r),  |r| < 1", desc: "Converges only for |r|<1." },
        ],
      },
      {
        id: "geometry",
        label: "Geometry",
        formulas: [
          { id: "geo-pyth", name: "Pythagorean Theorem", eq: "a² + b² = c²", desc: "Right-triangle side relation." },
          { id: "geo-carea", name: "Circle Area", eq: "A = πr²", desc: "Area of a circle." },
          { id: "geo-ccirc", name: "Circumference", eq: "C = 2πr", desc: "Perimeter of a circle." },
          { id: "geo-svol", name: "Sphere Volume", eq: "V = (4/3)πr³", desc: "Volume of a sphere." },
          { id: "geo-ssurf", name: "Sphere Surface Area", eq: "A = 4πr²", desc: "Surface area of a sphere." },
          { id: "geo-cyl", name: "Cylinder Volume", eq: "V = πr²h", desc: "Volume of a right cylinder." },
          { id: "geo-cone", name: "Cone Volume", eq: "V = (1/3)πr²h", desc: "Volume of a cone." },
          { id: "geo-tri", name: "Triangle Area", eq: "A = (1/2)bh", desc: "Base times height over two." },
          { id: "geo-heron", name: "Heron's Formula", eq: "A = √(s(s−a)(s−b)(s−c)),  s = (a+b+c)/2", desc: "Triangle area from side lengths." },
          { id: "geo-rect", name: "Rectangle Area", eq: "A = lw", desc: "Length times width." },
          { id: "geo-trap", name: "Trapezoid Area", eq: "A = (1/2)(b₁ + b₂)h", desc: "Average base times height." },
          { id: "geo-par", name: "Parallelogram Area", eq: "A = bh", desc: "Base times perpendicular height." },
        ],
      },
      {
        id: "trig",
        label: "Trigonometry",
        formulas: [
          { id: "trig-pythid", name: "Pythagorean Identity", eq: "sin²θ + cos²θ = 1", desc: "Fundamental trig identity." },
          { id: "trig-tan", name: "Tangent Identity", eq: "1 + tan²θ = sec²θ", desc: "Derived from sin²+cos²." },
          { id: "trig-cot", name: "Cotangent Identity", eq: "1 + cot²θ = csc²θ", desc: "Cotangent form of Pythagorean identity." },
          { id: "trig-sum", name: "Sine of Sum", eq: "sin(A±B) = sinA cosB ± cosA sinB", desc: "Angle addition for sine." },
          { id: "trig-cosum", name: "Cosine of Sum", eq: "cos(A±B) = cosA cosB ∓ sinA sinB", desc: "Angle addition for cosine." },
          { id: "trig-dbl", name: "Double Angle", eq: "sin2θ = 2 sinθ cosθ · cos2θ = cos²θ − sin²θ", desc: "Double-angle identities." },
          { id: "trig-losin", name: "Law of Sines", eq: "a/sinA = b/sinB = c/sinC = 2R", desc: "Sides vs angles; R = circumradius." },
          { id: "trig-locos", name: "Law of Cosines", eq: "c² = a² + b² − 2ab cosC", desc: "Generalized Pythagorean theorem." },
          { id: "trig-euler", name: "Euler's Formula", eq: "e^(iθ) = cosθ + i sinθ", desc: "Bridge between exponentials and trig." },
          { id: "trig-small", name: "Small-Angle Approx.", eq: "sin θ ≈ tan θ ≈ θ", desc: "Valid for θ in radians ≈ 0." },
        ],
      },
      {
        id: "calculus",
        label: "Calculus",
        formulas: [
          { id: "cal-deriv", name: "Derivative Definition", eq: "f'(x) = lim_{h→0} (f(x+h) − f(x)) / h", desc: "Limit definition of the derivative." },
          { id: "cal-power", name: "Power Rule", eq: "d/dx xⁿ = n xⁿ⁻¹", desc: "Derivative of a power." },
          { id: "cal-prod", name: "Product Rule", eq: "(uv)' = u'v + uv'", desc: "Derivative of a product." },
          { id: "cal-quot", name: "Quotient Rule", eq: "(u/v)' = (u'v − uv') / v²", desc: "Derivative of a quotient." },
          { id: "cal-chain", name: "Chain Rule", eq: "d/dx f(g(x)) = f'(g(x))·g'(x)", desc: "Derivative of a composition." },
          { id: "cal-intpow", name: "Power Integral", eq: "∫ xⁿ dx = xⁿ⁺¹/(n+1) + C,  n ≠ −1", desc: "Basic antiderivative." },
          { id: "cal-intexp", name: "Exponential Integral", eq: "∫ eˣ dx = eˣ + C", desc: "eˣ is its own antiderivative." },
          { id: "cal-intlog", name: "Log Integral", eq: "∫ (1/x) dx = ln|x| + C", desc: "Antiderivative of 1/x." },
          { id: "cal-inttrig", name: "Trig Integrals", eq: "∫ cos x dx = sin x + C · ∫ sin x dx = −cos x + C", desc: "Basic trig antiderivatives." },
          { id: "cal-ftc", name: "Fundamental Theorem", eq: "∫ₐᵇ f(x) dx = F(b) − F(a)", desc: "Links derivatives and integrals." },
          { id: "cal-taylor", name: "Taylor Series", eq: "f(x) = Σ f⁽ⁿ⁾(a)/n! · (x−a)ⁿ", desc: "Power-series expansion about a." },
          { id: "cal-euler", name: "Euler's Method", eq: "yₙ₊₁ = yₙ + h·f(xₙ, yₙ)", desc: "Numerical ODE step." },
        ],
      },
      {
        id: "linalg",
        label: "Linear Algebra",
        formulas: [
          { id: "la-dot", name: "Dot Product", eq: "a·b = |a||b|cosθ = Σ aᵢbᵢ", desc: "Scalar product of two vectors." },
          { id: "la-cross", name: "Cross Product", eq: "|a×b| = |a||b|sinθ", desc: "Vector product magnitude." },
          { id: "la-det", name: "Determinant (2×2)", eq: "|A| = ad − bc", desc: "For matrix [[a,b],[c,d]]." },
          { id: "la-inv", name: "Matrix Inverse", eq: "A⁻¹ = (1/|A|) adj(A)", desc: "Inverse via determinant and adjugate." },
          { id: "la-eigen", name: "Eigenvalue Equation", eq: "Av = λv", desc: "v is eigenvector, λ eigenvalue." },
          { id: "la-matmul", name: "Matrix Multiplication", eq: "(AB)ᵢⱼ = Σ Aᵢₖ Bₖⱼ", desc: "Row–column dot products." },
        ],
      },
      {
        id: "stats",
        label: "Statistics & Probability",
        formulas: [
          { id: "st-mean", name: "Mean", eq: "μ = (Σ xᵢ) / n", desc: "Arithmetic average." },
          { id: "st-var", name: "Variance", eq: "σ² = Σ(xᵢ − μ)² / n", desc: "Spread about the mean." },
          { id: "st-std", name: "Standard Deviation", eq: "σ = √(σ²)", desc: "Square root of variance." },
          { id: "st-z", name: "Z-Score", eq: "z = (x − μ) / σ", desc: "Standardized distance from mean." },
          { id: "st-bayes", name: "Bayes' Theorem", eq: "P(A|B) = P(B|A)·P(A) / P(B)", desc: "Update beliefs with evidence." },
          { id: "st-exp", name: "Expectation", eq: "E[X] = Σ xᵢ pᵢ", desc: "Weighted average of outcomes." },
          { id: "st-binom", name: "Binomial Probability", eq: "P(k) = C(n,k) pᵏ (1−p)ⁿ⁻ᵏ", desc: "k successes in n trials." },
          { id: "st-norm", name: "Normal Distribution", eq: "f(x) = (1/(σ√2π)) e^(−(x−μ)²/(2σ²))", desc: "Gaussian density." },
          { id: "st-corr", name: "Correlation", eq: "r = cov(X,Y) / (σ_X σ_Y)", desc: "Pearson correlation coefficient." },
        ],
      },
    ],
  },
  {
    id: "physics",
    label: "Physics",
    categories: [
      {
        id: "kinematics",
        label: "Kinematics",
        formulas: [
          { id: "kin-v", name: "Velocity (const. a)", eq: "v = u + at", desc: "u = initial velocity." },
          { id: "kin-s", name: "Displacement", eq: "s = ut + ½at²", desc: "Position under constant accel." },
          { id: "kin-v2", name: "Velocity-Squared", eq: "v² = u² + 2as", desc: "Time-free kinematic relation." },
          { id: "kin-avg", name: "Average Velocity", eq: "s = ½(u + v)t", desc: "Mean of initial/final velocity." },
          { id: "kin-proj", name: "Projectile Motion", eq: "x = v₀cosθ·t · y = v₀sinθ·t − ½gt²", desc: "2D trajectory under gravity." },
        ],
      },
      {
        id: "dynamics",
        label: "Dynamics & Energy",
        formulas: [
          { id: "dyn-n2", name: "Newton's 2nd Law", eq: "F = ma", desc: "Net force equals mass × acceleration." },
          { id: "dyn-n3", name: "Newton's 3rd Law", eq: "F_AB = −F_BA", desc: "Equal and opposite reactions." },
          { id: "dyn-fric", name: "Friction", eq: "f = μN", desc: "Kinetic/static friction force." },
          { id: "dyn-weight", name: "Weight", eq: "W = mg", desc: "Gravitational force on mass m." },
          { id: "dyn-mom", name: "Momentum", eq: "p = mv", desc: "Linear momentum." },
          { id: "dyn-imp", name: "Impulse", eq: "J = FΔt = Δp", desc: "Impulse equals momentum change." },
          { id: "dyn-work", name: "Work", eq: "W = Fd cosθ", desc: "Force × displacement along force." },
          { id: "dyn-ke", name: "Kinetic Energy", eq: "KE = ½mv²", desc: "Energy of motion." },
          { id: "dyn-pe", name: "Gravitational PE", eq: "PE = mgh", desc: "Near-surface potential energy." },
          { id: "dyn-spring", name: "Spring PE", eq: "U = ½kx²", desc: "Elastic potential (Hooke's law)." },
          { id: "dyn-pow", name: "Power", eq: "P = W/t = Fv", desc: "Rate of doing work." },
          { id: "dyn-consmom", name: "Conservation of Momentum", eq: "Σpᵢ = Σp_f", desc: "Isolated system, no external force." },
        ],
      },
      {
        id: "rotation",
        label: "Rotation",
        formulas: [
          { id: "rot-tau", name: "Torque", eq: "τ = rF sinθ", desc: "Rotational force." },
          { id: "rot-n2", name: "Rotational 2nd Law", eq: "τ = Iα", desc: "I = moment of inertia, α = angular accel." },
          { id: "rot-inert", name: "Moment of Inertia", eq: "I = Σmr²", desc: "Resistance to angular accel." },
          { id: "rot-ke", name: "Rotational KE", eq: "KE = ½Iω²", desc: "Energy of rotation." },
          { id: "rot-tan", name: "Tangential Relation", eq: "v = rω · a_t = rα", desc: "Linear ↔ angular quantities." },
        ],
      },
      {
        id: "gravity",
        label: "Gravitation & Orbits",
        formulas: [
          { id: "grav-law", name: "Newton's Law of Gravitation", eq: "F = G m₁m₂ / r²", desc: "Attractive force between masses." },
          { id: "grav-g", name: "Surface Gravity", eq: "g = GM / r²", desc: "Acceleration due to a body." },
          { id: "grav-orb", name: "Orbital Velocity", eq: "v = √(GM / r)", desc: "Speed for circular orbit." },
          { id: "grav-kepler", name: "Kepler's 3rd Law", eq: "T² = (4π² / GM) a³", desc: "Period vs semi-major axis." },
          { id: "grav-esc", name: "Escape Velocity", eq: "v_e = √(2GM / r)", desc: "Minimum speed to leave a body." },
          { id: "grav-pe", name: "Gravitational PE (general)", eq: "U = −GMm / r", desc: "Potential energy at distance r." },
        ],
      },
      {
        id: "thermo",
        label: "Thermodynamics",
        formulas: [
          { id: "th-ideal", name: "Ideal Gas Law", eq: "PV = nRT", desc: "R = 8.314 J/(mol·K)." },
          { id: "th-first", name: "1st Law of Thermodynamics", eq: "ΔU = Q − W", desc: "Energy conservation; Q in, W out." },
          { id: "th-heat", name: "Heat Transfer", eq: "Q = mcΔT", desc: "Sensible heat to raise temp." },
          { id: "th-latent", name: "Latent Heat", eq: "Q = mL", desc: "Heat for phase change." },
          { id: "th-carnot", name: "Carnot Efficiency", eq: "η = 1 − T_c / T_h", desc: "Max heat-engine efficiency." },
          { id: "th-stefan", name: "Stefan-Boltzmann Law", eq: "P = εσA T⁴", desc: "Radiated power of a blackbody." },
          { id: "th-wien", name: "Wien's Displacement Law", eq: "λ_max = b / T", desc: "Peak wavelength vs temperature." },
          { id: "th-entropy", name: "Entropy Change", eq: "ΔS = ΔQ / T", desc: "Reversible process entropy." },
        ],
      },
      {
        id: "waves",
        label: "Waves & Oscillations",
        formulas: [
          { id: "wav-shm", name: "Simple Harmonic Motion", eq: "x = A cos(ωt + φ)", desc: "Displacement of an oscillator." },
          { id: "wav-spring", name: "Spring Period", eq: "T = 2π√(m / k)", desc: "ω = √(k/m)." },
          { id: "wav-pend", name: "Pendulum Period", eq: "T = 2π√(L / g)", desc: "Small-angle simple pendulum." },
          { id: "wav-speed", name: "Wave Speed", eq: "v = fλ", desc: "Frequency × wavelength." },
          { id: "wav-eq", name: "Traveling Wave", eq: "y = A sin(kx − ωt)", desc: "k = 2π/λ, ω = 2πf." },
          { id: "wav-doppler", name: "Doppler Effect", eq: "f' = f (v ± v_o) / (v ∓ v_s)", desc: "Observed frequency shift." },
          { id: "wav-int", name: "Intensity", eq: "I = P / A", desc: "Power per unit area." },
        ],
      },
      {
        id: "em",
        label: "Electromagnetism",
        formulas: [
          { id: "em-coul", name: "Coulomb's Law", eq: "F = k q₁q₂ / r²", desc: "Force between point charges." },
          { id: "em-field", name: "Electric Field", eq: "E = F/q = kQ / r²", desc: "Field of a point charge." },
          { id: "em-pot", name: "Electric Potential", eq: "V = kQ / r · V = Ed", desc: "Potential from a charge / uniform field." },
          { id: "em-cap", name: "Capacitance", eq: "C = Q / V · C = ε₀A / d", desc: "Parallel-plate capacitance." },
          { id: "em-ohm", name: "Ohm's Law", eq: "V = IR", desc: "Voltage = current × resistance." },
          { id: "em-pow", name: "Electric Power", eq: "P = IV = I²R = V²/R", desc: "Power dissipated in a resistor." },
          { id: "em-series", name: "Resistors (series/parallel)", eq: "R_s = ΣRᵢ · 1/R_p = Σ(1/Rᵢ)", desc: "Combine resistances." },
          { id: "em-magf", name: "Magnetic Force", eq: "F = qvB sinθ", desc: "Force on a moving charge." },
          { id: "em-lorentz", name: "Lorentz Force", eq: "F = q(E + v×B)", desc: "Total EM force on a charge." },
          { id: "em-farad", name: "Faraday's Law", eq: "ε = −dΦ/dt", desc: "Induced EMF from flux change." },
          { id: "em-ampere", name: "Force Between Wires", eq: "F/L = μ₀ I₁I₂ / (2πr)", desc: "Parallel current-carrying wires." },
          { id: "em-maxwell", name: "Speed of Light", eq: "c = 1 / √(μ₀ε₀)", desc: "From Maxwell's equations." },
        ],
      },
      {
        id: "modern",
        label: "Modern Physics",
        formulas: [
          { id: "mod-photon", name: "Photon Energy", eq: "E = hf = hc / λ", desc: "Energy of a quantum of light." },
          { id: "mod-mass", name: "Mass-Energy Equivalence", eq: "E = mc²", desc: "Einstein's equivalence." },
          { id: "mod-time", name: "Time Dilation", eq: "Δt' = Δt / √(1 − v²/c²)", desc: "Moving clocks run slow." },
          { id: "mod-len", name: "Length Contraction", eq: "L' = L √(1 − v²/c²)", desc: "Moving lengths contract." },
          { id: "mod-mom", name: "Relativistic Momentum", eq: "p = γmv · γ = 1/√(1 − v²/c²)", desc: "Lorentz factor γ." },
          { id: "mod-broglie", name: "de Broglie Wavelength", eq: "λ = h / p", desc: "Wave nature of matter." },
          { id: "mod-unc", name: "Uncertainty Principle", eq: "Δx Δp ≥ ℏ/2", desc: "Heisenberg position-momentum limit." },
          { id: "mod-ryd", name: "Rydberg Formula", eq: "1/λ = R(1/n₁² − 1/n₂²)", desc: "Hydrogen spectral lines." },
          { id: "mod-decay", name: "Radioactive Decay", eq: "N = N₀ e^(−λt) · t½ = ln2 / λ", desc: "Exponential decay & half-life." },
        ],
      },
    ],
  },
  {
    id: "chemistry",
    label: "Chemistry",
    categories: [
      {
        id: "stoich",
        label: "Stoichiometry & Moles",
        formulas: [
          { id: "ch-moles", name: "Moles from Mass", eq: "n = m / M", desc: "M = molar mass (g/mol)." },
          { id: "ch-molar", name: "Molarity", eq: "C = n / V", desc: "Concentration in mol/L." },
          { id: "ch-stp", name: "Molar Volume (STP)", eq: "V = n · 22.4 L", desc: "One mole of ideal gas at STP." },
          { id: "ch-pct", name: "Percent Composition", eq: "% = (m_element / m_compound) × 100", desc: "Mass percent of an element." },
          { id: "ch-dilute", name: "Dilution", eq: "C₁V₁ = C₂V₂", desc: "Conserve moles on dilution." },
        ],
      },
      {
        id: "gas",
        label: "Gas Laws",
        formulas: [
          { id: "gas-boyle", name: "Boyle's Law", eq: "P₁V₁ = P₂V₂", desc: "Constant temperature." },
          { id: "gas-charles", name: "Charles's Law", eq: "V₁/T₁ = V₂/T₂", desc: "Constant pressure." },
          { id: "gas-combined", name: "Combined Gas Law", eq: "P₁V₁/T₁ = P₂V₂/T₂", desc: "Fixed amount of gas." },
          { id: "gas-ideal", name: "Ideal Gas Law", eq: "PV = nRT", desc: "R = 0.0821 L·atm/(mol·K)." },
          { id: "gas-graham", name: "Graham's Effusion", eq: "r₁/r₂ = √(M₂/M₁)", desc: "Rate ∝ 1/√molar mass." },
        ],
      },
      {
        id: "thermochem",
        label: "Thermochemistry",
        formulas: [
          { id: "tc-q", name: "Heat Capacity", eq: "q = mcΔT", desc: "Heat to change temperature." },
          { id: "tc-dh", name: "Heat from Enthalpy", eq: "q = nΔH", desc: "Heat at constant pressure." },
          { id: "tc-hess", name: "Hess's Law", eq: "ΔH_rxn = ΣΔH_products − ΣΔH_reactants", desc: "Enthalpy is state function." },
          { id: "tc-gibbs", name: "Gibbs Free Energy", eq: "ΔG = ΔH − TΔS", desc: "ΔG<0 → spontaneous." },
        ],
      },
      {
        id: "kinetics",
        label: "Kinetics & Equilibrium",
        formulas: [
          { id: "kn-rate", name: "Rate Law", eq: "rate = k[A]ᵐ[B]ⁿ", desc: "Reaction order = m+n." },
          { id: "kn-arr", name: "Arrhenius Equation", eq: "k = A e^(−Ea / RT)", desc: "Rate vs temperature." },
          { id: "kn-half", name: "First-Order Half-Life", eq: "t½ = ln2 / k", desc: "Independent of concentration." },
          { id: "kn-eq", name: "Equilibrium Constant", eq: "K = [products] / [reactants]", desc: "Each term raised to stoich power." },
        ],
      },
      {
        id: "acidbase",
        label: "Acids & Bases",
        formulas: [
          { id: "ab-ph", name: "pH", eq: "pH = −log[H⁺]", desc: "Hydronium concentration." },
          { id: "ab-poh", name: "pOH", eq: "pOH = −log[OH⁻]", desc: "Hydroxide concentration." },
          { id: "ab-sum", name: "pH + pOH", eq: "pH + pOH = 14", desc: "At 25 °C in water." },
          { id: "ab-hh", name: "Henderson-Hasselbalch", eq: "pH = pK_a + log([A⁻]/[HA])", desc: "Buffer pH." },
          { id: "ab-neut", name: "Neutralization", eq: "M_aV_a = M_bV_b", desc: "Acid-base titration equivalence." },
        ],
      },
    ],
  },
];